### ISSUE TITLE
More of a question about the hardcoded 127.0.0.1 in some of the templates

### ISSUE THREAD

**Issue by pmoosh** [bloomberg/kubernetes-cluster-cookbook#19]
Hi there,

tried to test the cookbook (master) with kubernetes 1.2. And I had a couple of questions, since I assume I used it wrong (All tests were done with a simple master, single minion):

For example I removed the 127.0.0.1 entries from the etc-etcd.erb template, otherwise services wouldn't start because they try to start a second time and fail because the ports are in use.

When I configure a minion, services will fail because they can't connect to etcd on (127.0.0.1).

One thought: 
You use chef search for the etcd setup and disable that when chef-solo is used. Would it be possible to disable it whenever a default['kubernetes']['etcd']['members'] is defined?

thanks

Peter

**Comment by rapenchukd** [comment]
The minions use 127.0.0.1 because in order to facilitate HA with multiple masters, haproxy also gets installed locally on the systems, haproxy will redirect localhost traffic to the desired location. it is possible your HAproxy didnt start because selinux denied it due to using ports that it sees as unusual- I have #16 to also set up SELINUX booleans if you dont want to use selinux disabled or permissive.

I think the issue with disabling the seach if the attribute is set- is that it will cause the attribute to never update on subsequent runs for those who wish to use search. you can use override['kubernetes']['etcd']['members'] and that will ignore what (if anything) search comes up with.

The master services shouldn't be trying to start a second time. are you able to supply a solo.json or any  node attributes you are overriding? the 127.0.0.1 is there so ETCD doesnt hit an external IP address for every read or write, and it also gives a predictable location for the local clients (flannel, apiserver) to communicate with.

**Comment by pmoosh** [comment]
Will look into it
thanks
Peter

**Comment by rapenchukd** [comment]
Of course, if you are still having issues along these lines, please reopen this! I am willing to work to get any kinks ironed out!

**Comment by pmoosh** [comment]
So I took out all my "changes" out over ride  node['kubernetes']['etcd']['members'] and do get this:

Apr 06 17:26:23 master-centos-71 etcd[14158]: Go Version: go1.4.2
Apr 06 17:26:23 master-centos-71 etcd[14158]: Go OS/Arch: linux/amd64
Apr 06 17:26:23 master-centos-71 etcd[14158]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Apr 06 17:26:23 master-centos-71 etcd[14158]: listening for peers on http://127.0.0.1:2380
Apr 06 17:26:23 master-centos-71 etcd[14158]: stopping listening for peers on http://127.0.0.1:2380
Apr 06 17:26:23 master-centos-71 etcd[14158]: listen tcp 127.0.0.1:2380: bind: address already in use
Apr 06 17:26:23 master-centos-71 systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
Apr 06 17:26:23 master-centos-71 systemd[1]: Failed to start Etcd Server.

etc.conf looks like this:
# File created by Chef! Any local changes will be overwritten next Chef run!

ETCD_NAME="master-centos-71"
ETCD_DATA_DIR="/var/lib/etcd/master-centos-71.etcd"
ETCD_INITIAL_CLUSTER_STATE="new"
ETCD_INITIAL_CLUSTER_TOKEN="newtoken"

ETCD_LISTEN_CLIENT_URLS="http://master-centos-71:2379,http://127.0.0.1:2379"
ETCD_LISTEN_PEER_URLS="http://master-centos-71:2380,http://127.0.0.1:2380"
ETCD_ADVERTISE_CLIENT_URLS="http://master-centos-71:2379"
ETCD_INITIAL_CLUSTER="master-centos-71=http://master-centos-71:2380,"
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://master-centos-71:2380"

# Secure ETCD configuration parameters go under here when node['kubernetes']['secure']['enabled'] == 'true'

**Comment by rapenchukd** [comment]
something seems wrong with the OS or package you are pulling...
Maybe something else is already listening on 127.0.0.1:2380?
Try changing node['kubernetes']['etcd']['peerport'] to something other than 2380. maybe 2381?

**Comment by pmoosh** [comment]
Again - my bad, DIdn't realize vagrant adds the hostname "master-centos-71" to 127.0.0.1 ...

**Comment by rapenchukd** [comment]
neither did I! Good to know, thanks!
